### ISSUE TITLE
RazzleDazzleDemo using a local folder /Users/laura_ifttt/...

### ISSUE THREAD

**Issue by gmertk** [IFTTT/RazzleDazzle#1]
Hi, 
I've just wanted to try the example app in Xcode7b4. So I built RazzleDazzle.framework and then RazzleDazzleDemo. But RazzleDazzleDemo build gives an error since it is looking for the framework in `/Users/laura_ifttt/Library/Developer/Xcode/`. 

So I had to move the built framework into the RazzleDazzleDemo project to run it. Is this expected or is there any way to point to a relative path?

**Comment by lauraskelton** [comment]
Oops good catch, I'll fix that!

**Comment by lauraskelton** [comment]
This should fix it - https://github.com/IFTTT/RazzleDazzle/commit/3eb9b1aa4638e3bca45b3b7097e83d18dc073f10

Thanks for pointing that out!

**Comment by gmertk** [comment]
Thank you! :+1:
