### ISSUE TITLE
Prebuilt binary for Swift 2.1

### ISSUE THREAD

**Issue by onevcat** [IFTTT/RazzleDazzle#10]
Xcode 7.1 prevent the using of prebuilt framework from Xcode 7 with this error:

> Module file was created by an older version of the compiler; rebuild 'RazzleDazzle' and try again: XXX/Carthage/Build/iOS/RazzleDazzle.framework/Modules/RazzleDazzle.swiftmodule/x86_64.swiftmodule

Would please rebuild it with Xcode 7.1 and archive a new framework for it? Thanks.

**Comment by ghost** [comment]
+1

**Comment by maxmeyers** [comment]
We're no longer including binaries in releases, since we'll just have to rebuild them overtime a new version of Xcode is released. If you still want to use an old version, you can add `--no-use-binaries` to your Carthage command.
