### ISSUE TITLE
How I can connect ViewController, that uses RazzleDazzle, with another ViewController correctly

### ISSUE THREAD

**Issue by miguelarauj1o** [IFTTT/RazzleDazzle#13]
Hello @lauraskelton, first of all, thanks for this awesome framework :)

I'm developing an app and I want to connect the introductory part (IntroViewController which uses `RazzleDazzle`) with a LoginViewController. I try add a UIButton over IntroViewController, but this button don't appear how I expected. How I can connect this Introdutory part with another ViewController correctly?

cc @FranclinC

**Comment by miguelarauj1o** [comment]
I fixed. So, I'm closing this issue.

**Comment by nharbo** [comment]
Maybe you could tell how you fixed it? :) Im facing the same issue..

**Comment by miguelarauj1o** [comment]
I can't remember anymore.
**sry**.
