### ISSUE TITLE
Page Change Listener

### ISSUE THREAD

**Issue by ArioSP93** [IFTTT/RazzleDazzle#15]
hi, is there a way to detect page change and get current page index?

**Comment by ArioSP93** [comment]
i've found the solution  

```
internal override func scrollViewDidScroll(scrollView: UIScrollView) {
    animateCurrentFrame()
    let screenSize: CGRect = UIScreen.mainScreen().bounds
    if scrollView.contentOffset.x%screenSize.width == 0 {
        let index = scrollView.contentOffset.x/screenSize.width
        print(index)
    }
}
```

**Comment by maxmeyers** [comment]
Glad you found a solution! I might recommend calling `super.scrollViewDidScroll(scrollView)` instead of `animateCurrentFrame()` so that you don't lose out on other superclass functionality.
