### ISSUE TITLE
Frameworks missing

### ISSUE THREAD

**Issue by bhavik616** [IFTTT/RazzleDazzle#16]
Hello there,
when i downloaded the project, the Nimble and Quick frameworks seem to be missing. As a result, i am not able to run the project.

**Comment by maxmeyers** [comment]
You should only need Quick & Nimble to build and run the tests. The example app (the target RazzleDazzleDemo) does not require either. In any case, you should use [Carthage](https://github.com/Carthage/Carthage) to install them with `carthage update`.
