### ISSUE TITLE
Soon to be deprecated NSLayoutConstraint methods

### ISSUE THREAD

**Issue by gonzalonunez** [IFTTT/RazzleDazzle#17]
Are there plans to move the use of -addConstraint, etc. over to the suggested methods? I'd be glad to submit the PR.

See:
<img width="1356" alt="screen shot 2016-02-13 at 11 38 27 pm" src="https://cloud.githubusercontent.com/assets/6403910/13031880/1ab4c6dc-d2ab-11e5-9f84-64c8eb5a0636.png">

**Comment by maxmeyers** [comment]
A PR would be welcome!

**Comment by gonzalonunez** [comment]
Cool! I'll get on it when I have the chance :+1:

**Comment by gonzalonunez** [comment]
PR: #18
