### ISSUE TITLE
nice work man! what does this line mean XD

### ISSUE THREAD

**Issue by zzz6519003** [IFTTT/RazzleDazzle#2]
:beer: 

```
    public var animations = [Animatable]()

```

**Comment by lauraskelton** [comment]
Thanks! That's just creating an array that can hold anything that conforms to the `Animatable` protocol. That means it's something we can call `animate(time)` on. Basically, it's an array that can hold any type of animation that will be animated together.

**Comment by zzz6519003** [comment]
thx!  so this part `[Animatable]`  means somthing conforms to protocol!  

and () create the array?
