### ISSUE TITLE
Version 1.3.0 is not downloadable with Cocoapods

### ISSUE THREAD

**Issue by kaandedeoglu** [IFTTT/RazzleDazzle#29]
<img width="412" alt="screen shot 2016-06-16 at 8 56 04 pm" src="https://cloud.githubusercontent.com/assets/1566836/16127358/cf3034a6-3404-11e6-803d-08b33a0eee3c.png">

It looks like the new podspec wasn't pushed to the trunk via `pod trunk push`.

**Comment by maxmeyers** [comment]
Thanks for letting us know, Kaan. Should be fixed now 👍
