### ISSUE TITLE
Swift 2.3 or 3 support?

### ISSUE THREAD

**Issue by rapgamestevejobs** [IFTTT/RazzleDazzle#32]
Hi, I love what you've built here!

Do you have any plans to make this work with Swift 2.3 or 3?

**Comment by huguesbr** [comment]
It seem like this fork is up to date: https://github.com/tcurdt/RazzleDazzle/ for Swift 3

**Comment by maxmeyers** [comment]
Swift 3 is now supported in release 0.1.4.
