### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by dimitris-c** [IFTTT/RazzleDazzle#39]
This also relies on Nimble & Quick to update their codebase to support swift 3.0

**Comment by tcurdt** [comment]
Seems like Quick and Nimble have merged swift3 support into master.

**Comment by dimitris-c** [comment]
There's now a PR #40 to support swift 3.0

**Comment by falkobuttler** [comment]
Any plans to merge the PR into master?

**Comment by maxmeyers** [comment]
This is complete in 0.1.4 via #31
