### ISSUE TITLE
Not building via Carthage 

### ISSUE THREAD

**Issue by ky1ejs** [IFTTT/RazzleDazzle#7]
I think this is because it's seeing the `.xcworkspace` before the `.xcodeproj`.

After this is fixed (or even if it's not), could you upload the framework to the latest release?

All you have to do is:

``` shell
$ carthage build --no-skip-current

$ carthage archive RazzleDazzle
```

Then upload the .zip in project root.

This will save tons of time on CI servers and will stop problems like this affecting users.

**Comment by lauraskelton** [comment]
@kylejm  That's a great suggestion, I'll get that added

**Comment by lauraskelton** [comment]
@kylejm I uploaded the framework to the release. Let me know if you still have issues getting it to work with Carthage - seems to be working for us!

**Comment by ky1ejs** [comment]
Hi Laura,

Thanks for sorting this! Sorry that I haven't been able to look at it yet - hopefully I can by early next week.
