### ISSUE TITLE
Build Failed with Xcode 6.4

### ISSUE THREAD

**Issue by manesvenom** [IFTTT/RazzleDazzle#8]
![screen shot 2015-08-24 at 3 52 09 pm](https://cloud.githubusercontent.com/assets/7610019/9435204/2d08f0ee-4a78-11e5-95ee-9c7735507145.png)

Deployment Target : 8.0
![screen shot 2015-08-24 at 3 54 21 pm](https://cloud.githubusercontent.com/assets/7610019/9435231/62282466-4a78-11e5-8a86-e526aa5ed7a6.png)

**Comment by lauraskelton** [comment]
@manesvenom Unfortunately there were breaking changes between Swift 1.2 (which is what's in Xcode 6.4), and Swift 2.0 (which is in the Xcode 7 betas). RazzleDazzle is built with Swift 2.0, so it won't build in Xcode 6.4. If you download the latest Xcode 7 beta, it will work.
