### ISSUE TITLE
RazzleDazzle Swift 1.2

### ISSUE THREAD

**Issue by masterfego** [IFTTT/RazzleDazzle#9]
I cant compile your examples, i can't integrate your Pod. I think you are your library is written is Swift 2.0.
Can you create a version for us?

**Comment by lauraskelton** [comment]
RazzleDazzle is written in Swift 2.0, so it will only compile in Xcode 7 and up. If you want to use a library like this that will integrate with an older version of Swift, you can use [JazzHands](https://github.com/IFTTT/JazzHands), which is written in Objective-C, and use a bridging header to access the methods from your Swift 1.2 classes.

**Comment by masterfego** [comment]
Okay, in your readme.md you can specify it too.

**Comment by lauraskelton** [comment]
Yup, it's under the notes section.

**Comment by lauraskelton** [comment]
I'll add the JazzHands suggestion, too.
